export interface SeedService {
  slug: string;
  name: string;
  category: string;
  description: string;
  price: number;
  duration: string;
  image: string;
  featured?: boolean;
  originalPrice?: number;
}

/* ─── Hair Services ─── */
export const services: SeedService[] = [
  {
    slug: "royal-nanoplasty",
    name: "Royal Nanoplasty",
    category: "Hair",
    description: "Advanced smoothing treatment for silky, frizz-free hair that lasts for months.",
    price: 450,
    duration: "5h",
    image: "/services/royal-nanoplasty.webp",
    featured: true,
  },
  {
    slug: "hair-consultation",
    name: "Hair Consultation",
    category: "Hair",
    description: "Personalized consultation with our expert stylists to plan your perfect look.",
    price: 1,
    duration: "15 min",
    image: "/services/hair-consultation.webp",
  },
  {
    slug: "fashion-shade-global-color",
    name: "Fashion Shade Global Hair Color",
    category: "Hair",
    description: "Full head global colour with trendy fashion shades for a bold, stunning transformation.",
    price: 200,
    duration: "2h 30m",
    image: "/services/fashion-shade-global-color.webp",
    featured: true,
  },
  {
    slug: "hair-root-touchup",
    name: "Hair Root Touch-Up",
    category: "Hair",
    description: "Quick and precise root colour touch-up to keep your hair looking fresh.",
    price: 80,
    duration: "45 min",
    image: "/services/hair-root-touchup.webp",
  },
  {
    slug: "hair-highlights-medium",
    name: "Hair Highlights (Medium)",
    category: "Hair",
    description: "Beautiful highlights for medium-length hair, adding dimension and radiance.",
    price: 300,
    duration: "4h",
    image: "/services/hair-highlights-medium.webp",
  },
  {
    slug: "hair-highlights-long",
    name: "Hair Highlights (Long)",
    category: "Hair",
    description: "Stunning highlights for long hair, creating depth and a sun-kissed glow.",
    price: 400,
    duration: "5h",
    image: "/services/hair-highlights-long.webp",
  },
  {
    slug: "global-with-highlights-short",
    name: "Global with Highlights (Short)",
    category: "Hair",
    description: "Full global colour combined with highlights for short hair — maximum impact.",
    price: 350,
    duration: "4h",
    image: "/services/global-with-highlights-short.webp",
  },
  {
    slug: "global-with-highlights-medium",
    name: "Global with Highlights (Medium)",
    category: "Hair",
    description: "Global colour paired with highlights for medium-length hair.",
    price: 450,
    duration: "4h 30m",
    image: "/services/global-with-highlights-medium.webp",
  },
  {
    slug: "global-with-highlights-long",
    name: "Global with Highlights (Long)",
    category: "Hair",
    description: "Luxurious global colour with highlights for long, flowing hair.",
    price: 550,
    duration: "5h 30m",
    image: "/services/global-with-highlights-long.webp",
  },
  {
    slug: "hair-cutting-basic",
    name: "Hair Cutting Basic",
    category: "Hair",
    description: "Precision cut and shape tailored to your face shape and personal style.",
    price: 63,
    originalPrice: 70,
    duration: "30 min",
    image: "/services/hair-cutting-basic.webp",
  },
  {
    slug: "kids-haircut",
    name: "Kids Haircut",
    category: "Hair",
    description: "Fun, gentle haircut experience designed specifically for children.",
    price: 75,
    duration: "1h",
    image: "/services/kids-haircut.webp",
  },
  {
    slug: "hair-cutting-advanced",
    name: "Hair Cutting Advanced",
    category: "Hair",
    description: "Expert precision cut with advanced techniques, styling and finishing.",
    price: 108,
    originalPrice: 120,
    duration: "1h",
    image: "/services/hair-cutting-advanced.webp",
    featured: true,
  },
  {
    slug: "silk-botox-smoothing-medium",
    name: "Silk Botox Smoothing (Medium)",
    category: "Hair",
    description: "Luxurious silk botox treatment to restore, smooth and add incredible shine to medium hair.",
    price: 350,
    duration: "4h",
    image: "/services/silk-botox-smoothing-medium.webp",
  },
  {
    slug: "silk-botox-smoothing-long",
    name: "Silk Botox Smoothing (Long)",
    category: "Hair",
    description: "Deep repair and smoothing for long hair with our premium silk botox formula.",
    price: 450,
    duration: "5h",
    image: "/services/silk-botox-smoothing-long.webp",
  },
  {
    slug: "silk-botox-smoothing-extra-long",
    name: "Silk Botox Smoothing (Extra Long)",
    category: "Hair",
    description: "Complete silk botox restoration for extra-long hair — ultimate smoothness and shine.",
    price: 600,
    duration: "6h",
    image: "/services/silk-botox-smoothing-extra-long.webp",
  },
  {
    slug: "keratin-treatment-medium",
    name: "Keratin Treatment (Medium)",
    category: "Hair",
    description: "Professional keratin smoothing for frizz-free, glossy, manageable medium-length hair.",
    price: 350,
    duration: "3h",
    image: "/services/keratin-treatment-medium.webp",
    featured: true,
  },
  {
    slug: "keratin-treatment-long",
    name: "Keratin Treatment (Long)",
    category: "Hair",
    description: "Premium keratin therapy for long hair — say goodbye to frizz forever.",
    price: 450,
    duration: "4h",
    image: "/services/keratin-treatment-long.webp",
  },
  {
    slug: "hair-spa-blast-dry",
    name: "Hair Spa — Blast Dry",
    category: "Hair",
    description: "Refreshing hair spa with blast dry for smooth, nourished and styled hair.",
    price: 77,
    originalPrice: 90,
    duration: "30 min",
    image: "/services/hair-spa-blast-dry.webp",
  },
  {
    slug: "hair-spa-blow-dry",
    name: "Hair Spa — Blow Dry",
    category: "Hair",
    description: "Indulgent hair spa treatment finished with a luxurious blow dry.",
    price: 128,
    originalPrice: 150,
    duration: "1h 15m",
    image: "/services/hair-spa-blow-dry.webp",
  },
  {
    slug: "ironing-short",
    name: "Ironing / Temporary Straightening (Short)",
    category: "Hair",
    description: "Quick ironing service for a sleek, straight look on short hair.",
    price: 43,
    originalPrice: 50,
    duration: "30 min",
    image: "/services/ironing-short.webp",
  },
  {
    slug: "ironing-long",
    name: "Ironing / Temporary Straightening (Long)",
    category: "Hair",
    description: "Expert straightening for long hair — sleek, glossy finish guaranteed.",
    price: 85,
    originalPrice: 100,
    duration: "45 min",
    image: "/services/ironing-long.webp",
  },
  {
    slug: "temporary-curls-short",
    name: "Temporary Curls (Short)",
    category: "Hair",
    description: "Bouncy, beautiful curls for short hair — perfect for any occasion.",
    price: 51,
    originalPrice: 60,
    duration: "30 min",
    image: "/services/temporary-curls-short.webp",
  },
  {
    slug: "temporary-curls-medium",
    name: "Temporary Curls (Medium)",
    category: "Hair",
    description: "Glamorous curls for medium-length hair that hold beautifully.",
    price: 72,
    originalPrice: 85,
    duration: "45 min",
    image: "/services/temporary-curls-medium.webp",
  },
  {
    slug: "temporary-curls-long",
    name: "Temporary Curls (Long)",
    category: "Hair",
    description: "Show-stopping curls for long hair — volume and bounce that lasts.",
    price: 102,
    originalPrice: 120,
    duration: "45 min",
    image: "/services/temporary-curls-long.webp",
  },
  {
    slug: "blow-dry",
    name: "Blow Dry",
    category: "Hair",
    description: "Professional blow dry for a smooth, voluminous finish.",
    price: 43,
    originalPrice: 50,
    duration: "30 min",
    image: "/services/blow-dry.webp",
  },
  {
    slug: "wash-conditioning-blast-dry",
    name: "Wash, Conditioning & Blast Dry",
    category: "Hair",
    description: "Deep cleansing wash with conditioning treatment and blast dry.",
    price: 51,
    originalPrice: 60,
    duration: "30 min",
    image: "/services/wash-conditioning-blast-dry.webp",
  },
  {
    slug: "hair-oil-massage-steam",
    name: "Hair Oil Massage with Steam & Wash",
    category: "Hair",
    description: "Therapeutic hair oil massage with steam treatment and wash for deep nourishment.",
    price: 110,
    duration: "30 min",
    image: "/services/hair-oil-massage-steam.webp",
  },
  {
    slug: "hair-oil-massage",
    name: "Hair Oil Massage",
    category: "Hair",
    description: "Relaxing oil massage to stimulate hair growth and relieve stress.",
    price: 72,
    originalPrice: 85,
    duration: "30 min",
    image: "/services/hair-oil-massage.webp",
  },
  {
    slug: "gray-hair-color-short",
    name: "Gray Hair Color Coverage (Short)",
    category: "Hair",
    description: "Full gray coverage for short hair with long-lasting, vibrant colour.",
    price: 100,
    duration: "45 min",
    image: "/services/gray-hair-color-short.webp",
  },
  {
    slug: "gray-hair-color-medium",
    name: "Gray Hair Color Coverage (Medium)",
    category: "Hair",
    description: "Complete gray coverage for medium hair with premium colour products.",
    price: 150,
    duration: "1h",
    image: "/services/gray-hair-color-medium.webp",
  },
  {
    slug: "gray-hair-color-long",
    name: "Gray Hair Color Coverage (Long)",
    category: "Hair",
    description: "Full gray coverage for long hair — natural, vibrant results.",
    price: 200,
    duration: "1h 30m",
    image: "/services/gray-hair-color-long.webp",
  },
];

/* ─── Makeup & Styling Services ─── */
export const makeupServices: SeedService[] = [
  {
    slug: "party-makeup",
    name: "Party Makeup",
    category: "Makeup & Styling",
    description: "Glamorous, photo-ready makeup for parties, galas and special evenings.",
    price: 120,
    duration: "1h",
    image: "/services/party-makeup.webp",
    featured: true,
  },
  {
    slug: "hair-do-basic",
    name: "Hair Do — Basic",
    category: "Makeup & Styling",
    description: "Elegant basic hairstyling for everyday occasions and casual events.",
    price: 100,
    duration: "1h",
    image: "/services/hair-do-basic.webp",
  },
  {
    slug: "hair-do-advanced",
    name: "Hair Do — Advanced",
    category: "Makeup & Styling",
    description: "Intricate, show-stopping hairstyling for weddings and special celebrations.",
    price: 200,
    duration: "1h 30m",
    image: "/services/hair-do-advanced.webp",
    featured: true,
  },
  {
    slug: "hd-party-makeup",
    name: "HD Party Makeup",
    category: "Makeup & Styling",
    description: "High-definition party makeup for a flawless, camera-ready look.",
    price: 200,
    duration: "1h 30m",
    image: "/services/hd-party-makeup.webp",
  },
  {
    slug: "bridal-makeup",
    name: "Bridal Makeup",
    category: "Makeup & Styling",
    description: "A flawless, long-wearing bridal look crafted by our master artists for your most important day.",
    price: 450,
    duration: "2h",
    image: "/services/bridal-makeup.webp",
    featured: true,
  },
  {
    slug: "bridal-hairstyle",
    name: "Bridal Hairstyle",
    category: "Makeup & Styling",
    description: "Exquisite bridal hairstyling to complement your wedding day look perfectly.",
    price: 230,
    duration: "2h 30m",
    image: "/services/bridal-hairstyle.webp",
    featured: true,
  },
  {
    slug: "saree-dupatta-draping",
    name: "Saree / Dupatta Draping",
    category: "Makeup & Styling",
    description: "Professional saree and dupatta draping for weddings and festive occasions.",
    price: 60,
    duration: "30 min",
    image: "/services/saree-dupatta-draping.webp",
  },
];

/* ─── Threading Services ─── */
export const threadingServices: SeedService[] = [
  {
    slug: "threading-combo",
    name: "Threading Combo",
    category: "Threading",
    description: "Complete threading combo — eyebrows, forehead, upper lip and chin in one session.",
    price: 40,
    duration: "35 min",
    image: "/services/threading-combo.webp",
    featured: true,
  },
  {
    slug: "eyebrow-wax",
    name: "Eyebrow Wax",
    category: "Threading",
    description: "Quick eyebrow shaping with warm wax for smooth, long-lasting results.",
    price: 35,
    duration: "30 min",
    image: "/services/eyebrow-wax.webp",
  },
  {
    slug: "forehead-threading",
    name: "Forehead Threading",
    category: "Threading",
    description: "Hair removal from the forehead using precise threading technique.",
    price: 15,
    duration: "10 min",
    image: "/services/forehead-threading.webp",
  },
  {
    slug: "forehead-wax",
    name: "Forehead Wax",
    category: "Threading",
    description: "Smooth forehead with gentle wax hair removal.",
    price: 20,
    duration: "10 min",
    image: "/services/forehead-wax.webp",
  },
  {
    slug: "upper-lip-threading",
    name: "Upper Lip Threading",
    category: "Threading",
    description: "Quick and precise upper lip hair removal with threading.",
    price: 15,
    duration: "10 min",
    image: "/services/upper-lip-threading.webp",
  },
  {
    slug: "upper-lip-wax",
    name: "Upper Lip Wax",
    category: "Threading",
    description: "Gentle wax treatment for smooth upper lip area.",
    price: 20,
    duration: "10 min",
    image: "/services/upper-lip-wax.webp",
  },
  {
    slug: "lower-lip-threading",
    name: "Lower Lip Threading",
    category: "Threading",
    description: "Precise lower lip threading for a clean, smooth finish.",
    price: 15,
    duration: "10 min",
    image: "/services/lower-lip-threading.webp",
  },
  {
    slug: "lower-lip-wax",
    name: "Lower Lip Wax",
    category: "Threading",
    description: "Gentle wax hair removal for the lower lip area.",
    price: 20,
    duration: "10 min",
    image: "/services/lower-lip-wax.webp",
  },
  {
    slug: "chin-threading",
    name: "Chin Threading",
    category: "Threading",
    description: "Precise chin hair removal using traditional threading technique.",
    price: 15,
    duration: "10 min",
    image: "/services/chin-threading.webp",
  },
  {
    slug: "chin-wax",
    name: "Chin Wax",
    category: "Threading",
    description: "Smooth chin with gentle wax hair removal treatment.",
    price: 20,
    duration: "10 min",
    image: "/services/chin-wax.webp",
  },
  {
    slug: "side-lock-threading",
    name: "Side Lock / Side Face Threading",
    category: "Threading",
    description: "Threading for side face and sideburn area for a clean, defined look.",
    price: 30,
    duration: "15 min",
    image: "/services/side-lock-threading.webp",
  },
  {
    slug: "side-lock-wax",
    name: "Side Lock / Side Face Wax",
    category: "Threading",
    description: "Wax hair removal for side face and sideburn area.",
    price: 40,
    duration: "20 min",
    image: "/services/side-lock-wax.webp",
  },
  {
    slug: "full-face-threading",
    name: "Full Face Threading",
    category: "Threading",
    description: "Complete full face threading for a smooth, hair-free complexion.",
    price: 50,
    duration: "30 min",
    image: "/services/full-face-threading.webp",
    featured: true,
  },
  {
    slug: "full-face-wax",
    name: "Full Face Wax",
    category: "Threading",
    description: "Complete full face wax for smooth, radiant skin.",
    price: 50,
    duration: "30 min",
    image: "/services/full-face-wax.webp",
  },
  {
    slug: "full-face-eyebrows-threading",
    name: "Full Face + Eyebrows Threading",
    category: "Threading",
    description: "Complete full face threading including eyebrow shaping — the ultimate combo.",
    price: 65,
    duration: "30 min",
    image: "/services/full-face-eyebrows-threading.webp",
    featured: true,
  },
];

/* ─── Waxing Services ─── */
export const waxingServices: SeedService[] = [
  {
    slug: "brazilian-bikini-wax",
    name: "Brazilian Bikini Wax",
    category: "Waxing",
    description: "Expert Brazilian bikini wax with gentle, skin-friendly formulas.",
    price: 102,
    originalPrice: 120,
    duration: "45 min",
    image: "/services/brazilian-bikini-wax.webp",
  },
  {
    slug: "summer-wax",
    name: "Summer Wax",
    category: "Waxing",
    description: "Full summer-ready waxing package for a confident, carefree season.",
    price: 150,
    duration: "1h 30m",
    image: "/services/summer-wax.webp",
    featured: true,
  },
  {
    slug: "full-body-wax-no-bikini",
    name: "Full Body Wax (No Bikini)",
    category: "Waxing",
    description: "Complete full body waxing excluding bikini area — smooth from head to toe.",
    price: 275,
    duration: "2h 30m",
    image: "/services/full-body-wax-no-bikini.webp",
    featured: true,
  },
  {
    slug: "summer-wax-combo-2",
    name: "Summer Wax Combo 2",
    category: "Waxing",
    description: "Popular summer wax combo covering multiple areas in one session.",
    price: 175,
    duration: "1h 40m",
    image: "/services/summer-wax-combo-2.webp",
  },
  {
    slug: "full-arms-wax",
    name: "Full Arms Wax",
    category: "Waxing",
    description: "Smooth, hair-free arms with our gentle waxing treatment.",
    price: 51,
    originalPrice: 60,
    duration: "30 min",
    image: "/services/full-arms-wax.webp",
  },
  {
    slug: "underarms-wax",
    name: "Underarms Wax",
    category: "Waxing",
    description: "Quick and gentle underarm waxing for smooth, fresh results.",
    price: 30,
    originalPrice: 35,
    duration: "30 min",
    image: "/services/underarms-wax.webp",
  },
  {
    slug: "half-legs-wax",
    name: "Half Legs Wax",
    category: "Waxing",
    description: "Smooth half-legs with our soothing waxing treatment.",
    price: 60,
    originalPrice: 70,
    duration: "30 min",
    image: "/services/half-legs-wax.webp",
  },
  {
    slug: "full-legs-wax",
    name: "Full Legs Wax",
    category: "Waxing",
    description: "Complete full-leg waxing for silky smooth results that last.",
    price: 94,
    originalPrice: 110,
    duration: "40 min",
    image: "/services/full-legs-wax.webp",
  },
  {
    slug: "full-back-wax",
    name: "Full Back Wax",
    category: "Waxing",
    description: "Thorough back waxing for smooth, clear skin.",
    price: 77,
    originalPrice: 90,
    duration: "30 min",
    image: "/services/full-back-wax.webp",
  },
  {
    slug: "tummy-wax",
    name: "Tummy Wax",
    category: "Waxing",
    description: "Gentle tummy waxing for smooth, hair-free skin.",
    price: 43,
    originalPrice: 50,
    duration: "30 min",
    image: "/services/tummy-wax.webp",
  },
];

/* ─── Facial & Skin Care Services ─── */
export const facialServices: SeedService[] = [
  {
    slug: "tan-removal-facial",
    name: "Tan Removal Facial",
    category: "Facial & Skin Care",
    description: "Specialized facial to remove tan and restore your skin's natural brightness.",
    price: 102,
    originalPrice: 120,
    duration: "1h",
    image: "/services/tan-removal-facial.webp",
  },
  {
    slug: "facial-dry-skin",
    name: "Facial for Dry Skin",
    category: "Facial & Skin Care",
    description: "Hydrating facial specifically designed to nourish and replenish dry skin.",
    price: 102,
    originalPrice: 120,
    duration: "1h",
    image: "/services/facial-dry-skin.webp",
  },
  {
    slug: "facial-oily-skin",
    name: "Facial for Oily Skin",
    category: "Facial & Skin Care",
    description: "Deep cleansing facial to control oil, minimize pores and prevent breakouts.",
    price: 102,
    originalPrice: 120,
    duration: "1h",
    image: "/services/facial-oily-skin.webp",
  },
  {
    slug: "facial-sensitive-skin",
    name: "Facial for Sensitive Skin",
    category: "Facial & Skin Care",
    description: "Gentle, calming facial for sensitive skin using hypoallergenic products.",
    price: 119,
    originalPrice: 140,
    duration: "1h",
    image: "/services/facial-sensitive-skin.webp",
  },
  {
    slug: "hydra-facial",
    name: "Hydra Facial",
    category: "Facial & Skin Care",
    description: "Medical-grade hydradermabrasion for instantly radiant, plump and youthful skin.",
    price: 170,
    originalPrice: 200,
    duration: "1h 30m",
    image: "/services/hydra-facial.webp",
    featured: true,
  },
  {
    slug: "royal-facial",
    name: "Royal Facial",
    category: "Facial & Skin Care",
    description: "Our signature luxury facial with premium products for the ultimate glow.",
    price: 128,
    originalPrice: 150,
    duration: "1h",
    image: "/services/royal-facial.webp",
    featured: true,
  },
  {
    slug: "offer-summer-facial-wax",
    name: "Offer Summer Facial & Wax",
    category: "Facial & Skin Care",
    description: "Combined summer facial and waxing package — glow and go for the season.",
    price: 120,
    duration: "2h",
    image: "/services/offer-summer-facial-wax.webp",
  },
  {
    slug: "cleanup",
    name: "Cleanup",
    category: "Facial & Skin Care",
    description: "Quick deep cleansing cleanup to refresh and rejuvenate your skin.",
    price: 50,
    duration: "30 min",
    image: "/services/cleanup.webp",
  },
  {
    slug: "face-bleach",
    name: "Face Bleach",
    category: "Facial & Skin Care",
    description: "Gentle face bleaching for a brighter, more even complexion.",
    price: 30,
    duration: "30 min",
    image: "/services/face-bleach.webp",
  },
  {
    slug: "face-detan",
    name: "Face Detan",
    category: "Facial & Skin Care",
    description: "Effective de-tanning treatment to remove sun damage and restore natural skin tone.",
    price: 30,
    duration: "30 min",
    image: "/services/face-detan.webp",
  },
];

/* ─── Manicure & Pedicure Services ─── */
export const nailServices: SeedService[] = [
  {
    slug: "manicure",
    name: "Manicure",
    category: "Manicure & Pedicure",
    description: "Luxury manicure with nourishing care, shaping and flawless polish.",
    price: 90,
    duration: "45 min",
    image: "/services/manicure.webp",
    featured: true,
  },
  {
    slug: "pedicure",
    name: "Pedicure",
    category: "Manicure & Pedicure",
    description: "Indulgent spa pedicure that pampers and refreshes tired feet.",
    price: 120,
    duration: "1h",
    image: "/services/pedicure.webp",
    featured: true,
  },
];

/* ─── Combined All Services (used by the one-time/disaster-recovery seed script) ─── */
export const allServices: SeedService[] = [
  ...services,
  ...makeupServices,
  ...threadingServices,
  ...waxingServices,
  ...facialServices,
  ...nailServices,
];

const U = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

/* ─── Packages ─── */
export const packages = [
  {
    slug: "royal-bridal",
    name: "Royal Bridal Package",
    type: "Bridal",
    price: 3500,
    originalPrice: 4800,
    description: "The complete head-to-toe bridal transformation for your wedding day.",
    includes: [
      "Bridal HD makeup",
      "Hair styling & extensions",
      "Bridal mehndi (hands & feet)",
      "Pre-bridal facial & cleanup",
      "Manicure & pedicure",
      "Draping & accessories",
    ],
    benefits: ["Dedicated lead artist", "Trial session included", "On-location available"],
    image: U("photo-1519741497674-611481863552"),
    popular: true,
  },
  {
    slug: "glow-monthly",
    name: "Glow Monthly Membership",
    type: "Monthly",
    price: 900,
    originalPrice: 1400,
    description: "Stay radiant all month with our curated self-care membership.",
    includes: [
      "2 signature facials",
      "1 hydra facial",
      "2 blow-dry sessions",
      "1 manicure & pedicure",
      "Threading (unlimited)",
    ],
    benefits: ["Priority booking", "15% off add-ons", "Free skin consultation"],
    image: U("photo-1596178065887-1198b6148b2b"),
  },
  {
    slug: "seasonal-radiance",
    name: "Seasonal Radiance Package",
    type: "Seasonal",
    price: 1600,
    originalPrice: 2200,
    description: "A seasonal reset pampering experience for skin, hair and nails.",
    includes: [
      "Hydra facial",
      "Keratin treatment",
      "Hair spa",
      "Full-body waxing",
      "Spa pedicure",
    ],
    benefits: ["Complimentary head massage", "Seasonal gift box", "Refreshments"],
    image: U("photo-1616394584738-fc6e612e71b9"),
  },
];

/* ─── Courses ─── */
export const courses = [
  {
    slug: "professional-makeup-artistry",
    name: "Professional Makeup Artistry",
    duration: "8 Weeks",
    level: "Professional",
    price: 4500,
    description:
      "Master bridal, editorial and HD makeup with a complete professional kit and live model practice.",
    modules: ["Skin prep & theory", "Bridal & HD looks", "Editorial & airbrush", "Business of makeup"],
    certification: "Internationally Accredited Diploma",
    image: U("photo-1487412947147-5cebf100ffc2"),
  },
  {
    slug: "advanced-hair-styling",
    name: "Advanced Hair Styling",
    duration: "6 Weeks",
    level: "Professional",
    price: 3800,
    description:
      "Learn cutting, colouring, keratin and red-carpet styling from senior stylists.",
    modules: ["Cutting techniques", "Colour theory", "Keratin & treatments", "Bridal updos"],
    certification: "Professional Hair Certification",
    image: U("photo-1562322140-8baeececf3df"),
  },
  {
    slug: "skincare-facial-specialist",
    name: "Skincare & Facial Specialist",
    duration: "4 Weeks",
    level: "Beginner",
    price: 2800,
    description:
      "Become a certified facial therapist with hands-on training in advanced skincare.",
    modules: ["Skin analysis", "Facial protocols", "Hydra facial", "Client care"],
    certification: "Certified Skincare Therapist",
    image: U("photo-1616394584738-fc6e612e71b9"),
  },
  {
    slug: "master-mehndi-art",
    name: "Master Mehndi Art",
    duration: "3 Weeks",
    level: "Master",
    price: 2200,
    description:
      "Perfect intricate bridal henna design and build your freelance mehndi business.",
    modules: ["Pattern fundamentals", "Bridal motifs", "Arabic & Indo designs", "Speed & finishing"],
    certification: "Master Mehndi Artist Certificate",
    image: U("photo-1595407753234-0882f1e77954"),
  },
];

/* ─── Testimonials ─── */
export const testimonials = [
  {
    name: "Zofia Kowalska",
    role: "Bride",
    avatar: U("photo-1438761681033-6461ffad8d80", 200),
    rating: 5,
    quote:
      "My bridal look was beyond a dream. The team made me feel like royalty from the trial to the wedding day. Every detail was perfect.",
  },
  {
    name: "Maria Nowak",
    role: "Monthly Member",
    avatar: U("photo-1494790108377-be9c29b29330", 200),
    rating: 5,
    quote:
      "The Glow membership transformed my skin. The hydra facials are unmatched in Warsaw. Truly a luxury experience every visit.",
  },
  {
    name: "Anna Wiśniewska",
    role: "Academy Graduate",
    avatar: U("photo-1534528741775-53994a69daeb", 200),
    rating: 5,
    quote:
      "I completed the makeup artistry course and now run my own studio. The training was world-class and the mentors were so supportive.",
  },
  {
    name: "Katarzyna Lewandowska",
    role: "Regular Client",
    avatar: U("photo-1544005313-94ddf0286df2", 200),
    rating: 5,
    quote:
      "From hair colour to nails, the attention to detail is exceptional. The ambience feels like a five-star retreat.",
  },
  {
    name: "Julia Zielińska",
    role: "Party Makeup",
    avatar: U("photo-1502823403499-6ccfcf4fb453", 200),
    rating: 5,
    quote:
      "I get endless compliments every time. The artists truly understand luxury and elegance. My go-to salon for every event.",
  },
];

/* ─── Gallery ─── */
export const gallery = [
  { src: U("photo-1457972729786-0411a3b2b626"), category: "Bridal", alt: "Bridal makeover" },
  { src: U("photo-1560066984-138dadb4c035"), category: "Hair", alt: "Hair styling" },
  { src: U("photo-1487412947147-5cebf100ffc2"), category: "Makeup", alt: "Party makeup" },
  { src: U("photo-1604654894610-df63bc536371"), category: "Nails", alt: "Luxury manicure" },
  { src: U("photo-1570172619644-dfd03ed5d881"), category: "Skin", alt: "Facial treatment" },
  { src: U("photo-1595407753234-0882f1e77954"), category: "Mehndi", alt: "Bridal mehndi" },
  { src: U("photo-1519741497674-611481863552"), category: "Bridal", alt: "Bride portrait" },
  { src: U("photo-1527799820374-dcf8d9d4a388"), category: "Hair", alt: "Hair colouring" },
  { src: U("photo-1522337360788-8b13dee7a37e"), category: "Hair", alt: "Hair updo" },
  { src: U("photo-1512290923902-8a9f81dc236c"), category: "Skin", alt: "Glowing skin" },
  { src: U("photo-1519014816548-bf5fe059798b"), category: "Nails", alt: "Spa pedicure" },
  { src: U("photo-1596178065887-1198b6148b2b"), category: "Makeup", alt: "Glam makeup" },
];
